/*
 * The Clear BSD License
 * Copyright 2017-2018 NXP
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted (subject to the limitations in the disclaimer below) provided
 * that the following conditions are met:
 *
 * o Redistributions of source code must retain the above copyright notice, this list
 *   of conditions and the following disclaimer.
 *
 * o Redistributions in binary form must reproduce the above copyright notice, this
 *   list of conditions and the following disclaimer in the documentation and/or
 *   other materials provided with the distribution.
 *
 * o Neither the name of the copyright holder nor the names of its
 *   contributors may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE.
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v4.1
processor: MIMXRT1052xxxxB
package_id: MIMXRT1052DVL6B
mcu_data: ksdk2_0
processor_version: 0.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "board.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: L14, peripheral: LPUART1, signal: RX, pin_signal: GPIO_AD_B0_13, software_input_on: Disable, hysteresis_enable: Disable, pull_up_down_config: Pull_Down_100K_Ohm,
    pull_keeper_select: Keeper, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: K14, peripheral: LPUART1, signal: TX, pin_signal: GPIO_AD_B0_12, software_input_on: Disable, hysteresis_enable: Disable, pull_up_down_config: Pull_Down_100K_Ohm,
    pull_keeper_select: Keeper, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03u */

  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B0_12_LPUART1_TX,        /* GPIO_AD_B0_12 is configured as LPUART1_TX */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B0_13_LPUART1_RX,        /* GPIO_AD_B0_13 is configured as LPUART1_RX */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_B0_12_LPUART1_TX,        /* GPIO_AD_B0_12 PAD functional properties : */
      0x10B0u);                               /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Keeper
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Down
                                                 Hyst. Enable Field: Hysteresis Disabled */
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_B0_13_LPUART1_RX,        /* GPIO_AD_B0_13 PAD functional properties : */
      0x10B0u);                               /* Slew Rate Field: Slow Slew Rate
                                                 Drive Strength Field: R0/6
                                                 Speed Field: medium(100MHz)
                                                 Open Drain Enable Field: Open Drain Disabled
                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
                                                 Pull / Keep Select Field: Keeper
                                                 Pull Up / Down Config. Field: 100K Ohm Pull Down
                                                 Hyst. Enable Field: Hysteresis Disabled */
    const gpio_pin_config_t pinConfig = {
        .direction = kGPIO_DigitalOutput,
        .outputLogic = 1,
    };
#if 0
    IOMUXC_SetPinMux(IOMUXC_GPIO_B0_04_FLEXIO2_FLEXIO04, 0U);                   /* WR Pin*/
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_04_FLEXIO2_FLEXIO04, 0xF0B0u);

    IOMUXC_SetPinMux(IOMUXC_GPIO_B0_05_FLEXIO2_FLEXIO05, 0U);                   /* RD Pin*/
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_05_FLEXIO2_FLEXIO05, 0xF0B0u);

    IOMUXC_SetPinMux(IOMUXC_GPIO_B0_06_GPIO2_IO06, 0U);                         /* RS Pin*/
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_06_GPIO2_IO06, 0xF0B0u);
    GPIO_PinInit(LCD_RS_GPIO, LCD_RS_PIN, &pinConfig);

    IOMUXC_SetPinMux(IOMUXC_GPIO_B0_07_GPIO2_IO07, 0U);                         /* CS Pin*/
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_07_GPIO2_IO07, 0xF0B0u);
    GPIO_PinInit(LCD_CS_GPIO, LCD_CS_PIN, &pinConfig);
#endif
#if 1
    IOMUXC_SetPinMux(IOMUXC_GPIO_B0_00_FLEXIO2_FLEXIO00, 0U);                   /* WR Pin*/
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_00_FLEXIO2_FLEXIO00, 0xF0B0u);

    IOMUXC_SetPinMux(IOMUXC_GPIO_B0_01_FLEXIO2_FLEXIO01, 0U);                   /* RD Pin*/
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_01_FLEXIO2_FLEXIO01, 0xF0B0u);

    IOMUXC_SetPinMux(IOMUXC_GPIO_B0_02_GPIO2_IO02, 0U);                         /* RS Pin*/
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_02_GPIO2_IO02, 0xF0B0u);
    GPIO_PinInit(LCD_RS_GPIO, LCD_RS_PIN, &pinConfig);

    IOMUXC_SetPinMux(IOMUXC_GPIO_B0_03_GPIO2_IO03, 0U);                         /* CS Pin*/
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_03_GPIO2_IO03, 0xF0B0u);
    GPIO_PinInit(LCD_CS_GPIO, LCD_CS_PIN, &pinConfig);
#endif

    /* Data pins*/
    IOMUXC_SetPinMux(IOMUXC_GPIO_B0_12_FLEXIO2_FLEXIO12, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_B0_13_FLEXIO2_FLEXIO13, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_B0_14_FLEXIO2_FLEXIO14, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_B0_15_FLEXIO2_FLEXIO15, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_B1_00_FLEXIO2_FLEXIO16, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_B1_01_FLEXIO2_FLEXIO17, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_B1_02_FLEXIO2_FLEXIO18, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_B1_03_FLEXIO2_FLEXIO19, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_B1_04_FLEXIO2_FLEXIO20, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_B1_05_FLEXIO2_FLEXIO21, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_B1_06_FLEXIO2_FLEXIO22, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_B1_07_FLEXIO2_FLEXIO23, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_B1_08_FLEXIO2_FLEXIO24, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_B1_09_FLEXIO2_FLEXIO25, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_B1_10_FLEXIO2_FLEXIO26, 0U);
    IOMUXC_SetPinMux(IOMUXC_GPIO_B1_11_FLEXIO2_FLEXIO27, 0U);
    //IOMUXC_SetPinMux(IOMUXC_GPIO_B1_12_FLEXIO2_FLEXIO28, 0U);
    //IOMUXC_SetPinMux(IOMUXC_GPIO_B1_13_FLEXIO2_FLEXIO29, 0U);
    //IOMUXC_SetPinMux(IOMUXC_GPIO_B1_14_FLEXIO2_FLEXIO30, 0U);
    //IOMUXC_SetPinMux(IOMUXC_GPIO_B1_15_FLEXIO2_FLEXIO31, 0U);

    IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_12_FLEXIO2_FLEXIO12, 0x30B0u);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_13_FLEXIO2_FLEXIO13, 0x30B0u);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_14_FLEXIO2_FLEXIO14, 0x30B0u);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_15_FLEXIO2_FLEXIO15, 0x30B0u);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_00_FLEXIO2_FLEXIO16, 0x30B0u);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_01_FLEXIO2_FLEXIO17, 0x30B0u);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_02_FLEXIO2_FLEXIO18, 0x30B0u);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_03_FLEXIO2_FLEXIO19, 0x30B0u);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_04_FLEXIO2_FLEXIO20, 0x30B0u);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_05_FLEXIO2_FLEXIO21, 0x30B0u);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_06_FLEXIO2_FLEXIO22, 0x30B0u);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_07_FLEXIO2_FLEXIO23, 0x30B0u);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_08_FLEXIO2_FLEXIO24, 0x30B0u);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_09_FLEXIO2_FLEXIO25, 0x30B0u);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_10_FLEXIO2_FLEXIO26, 0x30B0u);
    IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_11_FLEXIO2_FLEXIO27, 0x30B0u);
    //IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_12_FLEXIO2_FLEXIO28, 0x30B0u);
    //IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_13_FLEXIO2_FLEXIO29, 0x30B0u);
    //IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_14_FLEXIO2_FLEXIO30, 0x30B0u);
    //IOMUXC_SetPinConfig(IOMUXC_GPIO_B1_15_FLEXIO2_FLEXIO31, 0x30B0u);
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
